export interface SensusGenerus {
  balitaL: number;
  balitaP: number;
  paudL: number;
  paudP: number;
  cabeRawitL: number;
  cabeRawitP: number;
  preRemajaL: number;
  preRemajaP: number;
  remajaL: number;
  remajaP: number;
  pranikahL: number;
  pranikahP: number;
}

export interface SensusJamaahItem {
  no: number;
  desa: string;
  kelompok: string;
  diupdatePada: string;
  jumlahKK: number;
  generus: SensusGenerus;
  menikahL: number;
  menikahP: number;
  duda: number;
  janda: number;
  lansiaL: number;
  lansiaP: number;
  totalL: number;
  totalP: number;
  total: number;
}

export const INITIAL_SENSUS_JAMAAH: SensusJamaahItem[] = [
  {
    "no": 1,
    "desa": "BONANG",
    "kelompok": "BINONG 1",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 40,
    "generus": {
      "balitaL": 7,
      "balitaP": 5,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 8,
      "cabeRawitP": 5,
      "preRemajaL": 0,
      "preRemajaP": 5,
      "remajaL": 6,
      "remajaP": 5,
      "pranikahL": 14,
      "pranikahP": 8
    },
    "menikahL": 30,
    "menikahP": 41,
    "duda": 0,
    "janda": 0,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 65,
    "totalP": 69,
    "total": 134
  },
  {
    "no": 2,
    "desa": "BONANG",
    "kelompok": "BINONG 2",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 41,
    "generus": {
      "balitaL": 4,
      "balitaP": 3,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 7,
      "cabeRawitP": 5,
      "preRemajaL": 4,
      "preRemajaP": 3,
      "remajaL": 1,
      "remajaP": 0,
      "pranikahL": 15,
      "pranikahP": 16
    },
    "menikahL": 30,
    "menikahP": 33,
    "duda": 0,
    "janda": 0,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 61,
    "totalP": 60,
    "total": 121
  },
  {
    "no": 3,
    "desa": "BONANG",
    "kelompok": "DASANA UTARA",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 33,
    "generus": {
      "balitaL": 3,
      "balitaP": 6,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 8,
      "cabeRawitP": 7,
      "preRemajaL": 0,
      "preRemajaP": 2,
      "remajaL": 2,
      "remajaP": 2,
      "pranikahL": 11,
      "pranikahP": 15
    },
    "menikahL": 33,
    "menikahP": 36,
    "duda": 0,
    "janda": 0,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 57,
    "totalP": 68,
    "total": 125
  },
  {
    "no": 4,
    "desa": "BONANG",
    "kelompok": "DASANA SELATAN",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 45,
    "generus": {
      "balitaL": 7,
      "balitaP": 4,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 11,
      "cabeRawitP": 7,
      "preRemajaL": 4,
      "preRemajaP": 3,
      "remajaL": 5,
      "remajaP": 3,
      "pranikahL": 5,
      "pranikahP": 3
    },
    "menikahL": 48,
    "menikahP": 47,
    "duda": 0,
    "janda": 0,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 80,
    "totalP": 67,
    "total": 147
  },
  {
    "no": 5,
    "desa": "BONANG",
    "kelompok": "KELAPA DUA",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 45,
    "generus": {
      "balitaL": 3,
      "balitaP": 3,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 7,
      "cabeRawitP": 2,
      "preRemajaL": 2,
      "preRemajaP": 2,
      "remajaL": 0,
      "remajaP": 3,
      "pranikahL": 12,
      "pranikahP": 17
    },
    "menikahL": 28,
    "menikahP": 45,
    "duda": 0,
    "janda": 0,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 52,
    "totalP": 72,
    "total": 124
  },
  {
    "no": 6,
    "desa": "BONANG",
    "kelompok": "LEGOK",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 42,
    "generus": {
      "balitaL": 9,
      "balitaP": 7,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 12,
      "cabeRawitP": 10,
      "preRemajaL": 3,
      "preRemajaP": 2,
      "remajaL": 6,
      "remajaP": 6,
      "pranikahL": 2,
      "pranikahP": 2
    },
    "menikahL": 35,
    "menikahP": 40,
    "duda": 0,
    "janda": 0,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 67,
    "totalP": 67,
    "total": 134
  },
  {
    "no": 7,
    "desa": "BONANG",
    "kelompok": "PARUNG PAJANG",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 38,
    "generus": {
      "balitaL": 3,
      "balitaP": 7,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 17,
      "cabeRawitP": 10,
      "preRemajaL": 3,
      "preRemajaP": 4,
      "remajaL": 0,
      "remajaP": 0,
      "pranikahL": 4,
      "pranikahP": 5
    },
    "menikahL": 40,
    "menikahP": 37,
    "duda": 0,
    "janda": 0,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 67,
    "totalP": 63,
    "total": 130
  },
  {
    "no": 8,
    "desa": "BSD",
    "kelompok": "BSD 1",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 45,
    "generus": {
      "balitaL": 8,
      "balitaP": 7,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 9,
      "cabeRawitP": 15,
      "preRemajaL": 3,
      "preRemajaP": 2,
      "remajaL": 1,
      "remajaP": 0,
      "pranikahL": 7,
      "pranikahP": 18
    },
    "menikahL": 41,
    "menikahP": 44,
    "duda": 0,
    "janda": 2,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 69,
    "totalP": 88,
    "total": 157
  },
  {
    "no": 9,
    "desa": "BSD",
    "kelompok": "BSD 2",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 26,
    "generus": {
      "balitaL": 3,
      "balitaP": 2,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 4,
      "cabeRawitP": 3,
      "preRemajaL": 0,
      "preRemajaP": 3,
      "remajaL": 2,
      "remajaP": 2,
      "pranikahL": 5,
      "pranikahP": 11
    },
    "menikahL": 34,
    "menikahP": 33,
    "duda": 0,
    "janda": 5,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 48,
    "totalP": 59,
    "total": 107
  },
  {
    "no": 10,
    "desa": "BSD",
    "kelompok": "CIBOGO",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 74,
    "generus": {
      "balitaL": 4,
      "balitaP": 6,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 5,
      "cabeRawitP": 13,
      "preRemajaL": 1,
      "preRemajaP": 0,
      "remajaL": 1,
      "remajaP": 2,
      "pranikahL": 14,
      "pranikahP": 19
    },
    "menikahL": 62,
    "menikahP": 67,
    "duda": 0,
    "janda": 2,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 87,
    "totalP": 109,
    "total": 196
  },
  {
    "no": 11,
    "desa": "BSD",
    "kelompok": "CISAUK",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 60,
    "generus": {
      "balitaL": 21,
      "balitaP": 21,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 14,
      "cabeRawitP": 14,
      "preRemajaL": 2,
      "preRemajaP": 6,
      "remajaL": 3,
      "remajaP": 5,
      "pranikahL": 24,
      "pranikahP": 16
    },
    "menikahL": 62,
    "menikahP": 65,
    "duda": 0,
    "janda": 3,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 126,
    "totalP": 130,
    "total": 256
  },
  {
    "no": 12,
    "desa": "BSD",
    "kelompok": "PAGEDANGAN",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 55,
    "generus": {
      "balitaL": 11,
      "balitaP": 6,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 19,
      "cabeRawitP": 11,
      "preRemajaL": 7,
      "preRemajaP": 6,
      "remajaL": 3,
      "remajaP": 1,
      "pranikahL": 9,
      "pranikahP": 10
    },
    "menikahL": 70,
    "menikahP": 60,
    "duda": 0,
    "janda": 4,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 119,
    "totalP": 98,
    "total": 217
  },
  {
    "no": 13,
    "desa": "BSD",
    "kelompok": "PONDOK JAGUNG",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 50,
    "generus": {
      "balitaL": 6,
      "balitaP": 3,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 10,
      "cabeRawitP": 12,
      "preRemajaL": 5,
      "preRemajaP": 2,
      "remajaL": 6,
      "remajaP": 4,
      "pranikahL": 17,
      "pranikahP": 15
    },
    "menikahL": 37,
    "menikahP": 41,
    "duda": 0,
    "janda": 1,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 81,
    "totalP": 78,
    "total": 159
  },
  {
    "no": 14,
    "desa": "BSD",
    "kelompok": "BSD WORTEL",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 42,
    "generus": {
      "balitaL": 3,
      "balitaP": 3,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 6,
      "cabeRawitP": 3,
      "preRemajaL": 2,
      "preRemajaP": 1,
      "remajaL": 1,
      "remajaP": 0,
      "pranikahL": 4,
      "pranikahP": 6
    },
    "menikahL": 37,
    "menikahP": 41,
    "duda": 0,
    "janda": 0,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 53,
    "totalP": 54,
    "total": 107
  },
  {
    "no": 15,
    "desa": "BSD",
    "kelompok": "SURADITA",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 26,
    "generus": {
      "balitaL": 7,
      "balitaP": 0,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 6,
      "cabeRawitP": 3,
      "preRemajaL": 1,
      "preRemajaP": 1,
      "remajaL": 0,
      "remajaP": 0,
      "pranikahL": 4,
      "pranikahP": 7
    },
    "menikahL": 18,
    "menikahP": 22,
    "duda": 0,
    "janda": 5,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 36,
    "totalP": 38,
    "total": 74
  },
  {
    "no": 16,
    "desa": "CIBODASARI",
    "kelompok": "PERUM 1A",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 37,
    "generus": {
      "balitaL": 0,
      "balitaP": 2,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 3,
      "cabeRawitP": 4,
      "preRemajaL": 2,
      "preRemajaP": 1,
      "remajaL": 0,
      "remajaP": 3,
      "pranikahL": 14,
      "pranikahP": 13
    },
    "menikahL": 26,
    "menikahP": 24,
    "duda": 1,
    "janda": 6,
    "lansiaL": 5,
    "lansiaP": 5,
    "totalL": 46,
    "totalP": 53,
    "total": 99
  },
  {
    "no": 17,
    "desa": "CIBODASARI",
    "kelompok": "PERUM 1B",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 33,
    "generus": {
      "balitaL": 2,
      "balitaP": 0,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 9,
      "cabeRawitP": 8,
      "preRemajaL": 3,
      "preRemajaP": 1,
      "remajaL": 2,
      "remajaP": 6,
      "pranikahL": 14,
      "pranikahP": 6
    },
    "menikahL": 29,
    "menikahP": 28,
    "duda": 1,
    "janda": 1,
    "lansiaL": 6,
    "lansiaP": 5,
    "totalL": 60,
    "totalP": 50,
    "total": 110
  },
  {
    "no": 18,
    "desa": "CIBODASARI",
    "kelompok": "PERUM 2",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 17,
    "generus": {
      "balitaL": 0,
      "balitaP": 2,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 4,
      "cabeRawitP": 4,
      "preRemajaL": 1,
      "preRemajaP": 2,
      "remajaL": 3,
      "remajaP": 1,
      "pranikahL": 11,
      "pranikahP": 12
    },
    "menikahL": 14,
    "menikahP": 13,
    "duda": 0,
    "janda": 3,
    "lansiaL": 5,
    "lansiaP": 2,
    "totalL": 33,
    "totalP": 37,
    "total": 70
  },
  {
    "no": 19,
    "desa": "CIBODASARI",
    "kelompok": "PERUM 3",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 47,
    "generus": {
      "balitaL": 2,
      "balitaP": 6,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 12,
      "cabeRawitP": 8,
      "preRemajaL": 4,
      "preRemajaP": 3,
      "remajaL": 3,
      "remajaP": 0,
      "pranikahL": 14,
      "pranikahP": 11
    },
    "menikahL": 47,
    "menikahP": 37,
    "duda": 1,
    "janda": 4,
    "lansiaL": 5,
    "lansiaP": 1,
    "totalL": 83,
    "totalP": 69,
    "total": 152
  },
  {
    "no": 20,
    "desa": "CIBODASARI",
    "kelompok": "PALEM SEMI",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 58,
    "generus": {
      "balitaL": 6,
      "balitaP": 3,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 22,
      "cabeRawitP": 31,
      "preRemajaL": 2,
      "preRemajaP": 2,
      "remajaL": 2,
      "remajaP": 3,
      "pranikahL": 12,
      "pranikahP": 8
    },
    "menikahL": 58,
    "menikahP": 48,
    "duda": 1,
    "janda": 8,
    "lansiaL": 7,
    "lansiaP": 4,
    "totalL": 103,
    "totalP": 103,
    "total": 206
  },
  {
    "no": 21,
    "desa": "CIMONE",
    "kelompok": "CIMONE 1",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 56,
    "generus": {
      "balitaL": 5,
      "balitaP": 11,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 17,
      "cabeRawitP": 11,
      "preRemajaL": 3,
      "preRemajaP": 3,
      "remajaL": 4,
      "remajaP": 1,
      "pranikahL": 14,
      "pranikahP": 19
    },
    "menikahL": 42,
    "menikahP": 51,
    "duda": 1,
    "janda": 9,
    "lansiaL": 4,
    "lansiaP": 7,
    "totalL": 86,
    "totalP": 105,
    "total": 191
  },
  {
    "no": 22,
    "desa": "CIMONE",
    "kelompok": "CIMONE 2",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 59,
    "generus": {
      "balitaL": 11,
      "balitaP": 5,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 22,
      "cabeRawitP": 12,
      "preRemajaL": 6,
      "preRemajaP": 3,
      "remajaL": 7,
      "remajaP": 4,
      "pranikahL": 19,
      "pranikahP": 24
    },
    "menikahL": 57,
    "menikahP": 59,
    "duda": 0,
    "janda": 10,
    "lansiaL": 9,
    "lansiaP": 11,
    "totalL": 122,
    "totalP": 117,
    "total": 239
  },
  {
    "no": 23,
    "desa": "CIMONE",
    "kelompok": "CIMONE 3",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 31,
    "generus": {
      "balitaL": 8,
      "balitaP": 8,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 10,
      "cabeRawitP": 12,
      "preRemajaL": 4,
      "preRemajaP": 3,
      "remajaL": 3,
      "remajaP": 1,
      "pranikahL": 12,
      "pranikahP": 8
    },
    "menikahL": 31,
    "menikahP": 25,
    "duda": 2,
    "janda": 4,
    "lansiaL": 1,
    "lansiaP": 2,
    "totalL": 70,
    "totalP": 61,
    "total": 131
  },
  {
    "no": 24,
    "desa": "CIMONE",
    "kelompok": "CIMONE PERMAI",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 14,
    "generus": {
      "balitaL": 3,
      "balitaP": 2,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 3,
      "cabeRawitP": 1,
      "preRemajaL": 2,
      "preRemajaP": 0,
      "remajaL": 0,
      "remajaP": 0,
      "pranikahL": 4,
      "pranikahP": 8
    },
    "menikahL": 10,
    "menikahP": 16,
    "duda": 0,
    "janda": 2,
    "lansiaL": 5,
    "lansiaP": 6,
    "totalL": 22,
    "totalP": 29,
    "total": 51
  },
  {
    "no": 25,
    "desa": "CIMONE",
    "kelompok": "KARAWACI",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 31,
    "generus": {
      "balitaL": 0,
      "balitaP": 1,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 7,
      "cabeRawitP": 8,
      "preRemajaL": 3,
      "preRemajaP": 3,
      "remajaL": 4,
      "remajaP": 2,
      "pranikahL": 10,
      "pranikahP": 10
    },
    "menikahL": 19,
    "menikahP": 30,
    "duda": 1,
    "janda": 8,
    "lansiaL": 8,
    "lansiaP": 11,
    "totalL": 44,
    "totalP": 62,
    "total": 106
  },
  {
    "no": 26,
    "desa": "CIMONE",
    "kelompok": "TAMAN CIBODAS",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 14,
    "generus": {
      "balitaL": 3,
      "balitaP": 0,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 4,
      "cabeRawitP": 4,
      "preRemajaL": 1,
      "preRemajaP": 3,
      "remajaL": 2,
      "remajaP": 4,
      "pranikahL": 5,
      "pranikahP": 4
    },
    "menikahL": 15,
    "menikahP": 16,
    "duda": 1,
    "janda": 4,
    "lansiaL": 3,
    "lansiaP": 4,
    "totalL": 31,
    "totalP": 35,
    "total": 66
  },
  {
    "no": 27,
    "desa": "KENANGA",
    "kelompok": "KENANGA 1",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 38,
    "generus": {
      "balitaL": 9,
      "balitaP": 6,
      "paudL": 6,
      "paudP": 5,
      "cabeRawitL": 5,
      "cabeRawitP": 7,
      "preRemajaL": 2,
      "preRemajaP": 3,
      "remajaL": 5,
      "remajaP": 6,
      "pranikahL": 10,
      "pranikahP": 9
    },
    "menikahL": 32,
    "menikahP": 33,
    "duda": 2,
    "janda": 3,
    "lansiaL": 4,
    "lansiaP": 2,
    "totalL": 71,
    "totalP": 72,
    "total": 143
  },
  {
    "no": 28,
    "desa": "KENANGA",
    "kelompok": "KENANGA 2",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 53,
    "generus": {
      "balitaL": 6,
      "balitaP": 7,
      "paudL": 7,
      "paudP": 2,
      "cabeRawitL": 18,
      "cabeRawitP": 8,
      "preRemajaL": 5,
      "preRemajaP": 9,
      "remajaL": 9,
      "remajaP": 6,
      "pranikahL": 19,
      "pranikahP": 23
    },
    "menikahL": 42,
    "menikahP": 46,
    "duda": 0,
    "janda": 5,
    "lansiaL": 2,
    "lansiaP": 3,
    "totalL": 106,
    "totalP": 106,
    "total": 212
  },
  {
    "no": 29,
    "desa": "KENANGA",
    "kelompok": "KENANGA 3",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 51,
    "generus": {
      "balitaL": 9,
      "balitaP": 9,
      "paudL": 3,
      "paudP": 5,
      "cabeRawitL": 11,
      "cabeRawitP": 14,
      "preRemajaL": 4,
      "preRemajaP": 7,
      "remajaL": 4,
      "remajaP": 6,
      "pranikahL": 20,
      "pranikahP": 13
    },
    "menikahL": 42,
    "menikahP": 47,
    "duda": 0,
    "janda": 6,
    "lansiaL": 4,
    "lansiaP": 3,
    "totalL": 93,
    "totalP": 107,
    "total": 200
  },
  {
    "no": 30,
    "desa": "KENANGA",
    "kelompok": "KENANGA 4",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 44,
    "generus": {
      "balitaL": 6,
      "balitaP": 2,
      "paudL": 4,
      "paudP": 7,
      "cabeRawitL": 13,
      "cabeRawitP": 16,
      "preRemajaL": 5,
      "preRemajaP": 3,
      "remajaL": 3,
      "remajaP": 2,
      "pranikahL": 17,
      "pranikahP": 7
    },
    "menikahL": 38,
    "menikahP": 41,
    "duda": 1,
    "janda": 2,
    "lansiaL": 2,
    "lansiaP": 3,
    "totalL": 87,
    "totalP": 80,
    "total": 167
  },
  {
    "no": 31,
    "desa": "KENANGA",
    "kelompok": "KENANGA 5",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 41,
    "generus": {
      "balitaL": 9,
      "balitaP": 7,
      "paudL": 2,
      "paudP": 4,
      "cabeRawitL": 13,
      "cabeRawitP": 17,
      "preRemajaL": 3,
      "preRemajaP": 5,
      "remajaL": 1,
      "remajaP": 4,
      "pranikahL": 6,
      "pranikahP": 6
    },
    "menikahL": 36,
    "menikahP": 38,
    "duda": 0,
    "janda": 3,
    "lansiaL": 3,
    "lansiaP": 1,
    "totalL": 70,
    "totalP": 84,
    "total": 154
  },
  {
    "no": 32,
    "desa": "KENANGA",
    "kelompok": "KENANGA 6",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 32,
    "generus": {
      "balitaL": 1,
      "balitaP": 3,
      "paudL": 4,
      "paudP": 1,
      "cabeRawitL": 9,
      "cabeRawitP": 11,
      "preRemajaL": 3,
      "preRemajaP": 2,
      "remajaL": 1,
      "remajaP": 1,
      "pranikahL": 13,
      "pranikahP": 5
    },
    "menikahL": 30,
    "menikahP": 29,
    "duda": 0,
    "janda": 6,
    "lansiaL": 1,
    "lansiaP": 4,
    "totalL": 61,
    "totalP": 58,
    "total": 119
  },
  {
    "no": 33,
    "desa": "KENANGA",
    "kelompok": "CIPONDOH MAKMUR",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 26,
    "generus": {
      "balitaL": 2,
      "balitaP": 1,
      "paudL": 3,
      "paudP": 2,
      "cabeRawitL": 4,
      "cabeRawitP": 4,
      "preRemajaL": 2,
      "preRemajaP": 0,
      "remajaL": 1,
      "remajaP": 1,
      "pranikahL": 14,
      "pranikahP": 9
    },
    "menikahL": 23,
    "menikahP": 25,
    "duda": 2,
    "janda": 2,
    "lansiaL": 12,
    "lansiaP": 7,
    "totalL": 51,
    "totalP": 44,
    "total": 95
  },
  {
    "no": 34,
    "desa": "NEGLASARI",
    "kelompok": "SEKARWANGI UTARA",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 46,
    "generus": {
      "balitaL": 5,
      "balitaP": 7,
      "paudL": 5,
      "paudP": 6,
      "cabeRawitL": 18,
      "cabeRawitP": 23,
      "preRemajaL": 0,
      "preRemajaP": 4,
      "remajaL": 3,
      "remajaP": 0,
      "pranikahL": 21,
      "pranikahP": 20
    },
    "menikahL": 51,
    "menikahP": 44,
    "duda": 4,
    "janda": 3,
    "lansiaL": 2,
    "lansiaP": 1,
    "totalL": 107,
    "totalP": 107,
    "total": 214
  },
  {
    "no": 35,
    "desa": "NEGLASARI",
    "kelompok": "SEKARWANGI SELATAN",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 40,
    "generus": {
      "balitaL": 9,
      "balitaP": 6,
      "paudL": 11,
      "paudP": 3,
      "cabeRawitL": 16,
      "cabeRawitP": 8,
      "preRemajaL": 5,
      "preRemajaP": 1,
      "remajaL": 5,
      "remajaP": 4,
      "pranikahL": 10,
      "pranikahP": 10
    },
    "menikahL": 34,
    "menikahP": 39,
    "duda": 0,
    "janda": 2,
    "lansiaL": 3,
    "lansiaP": 2,
    "totalL": 90,
    "totalP": 73,
    "total": 163
  },
  {
    "no": 36,
    "desa": "NEGLASARI",
    "kelompok": "SELAPAJANG",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 26,
    "generus": {
      "balitaL": 11,
      "balitaP": 5,
      "paudL": 4,
      "paudP": 4,
      "cabeRawitL": 4,
      "cabeRawitP": 9,
      "preRemajaL": 3,
      "preRemajaP": 3,
      "remajaL": 4,
      "remajaP": 2,
      "pranikahL": 15,
      "pranikahP": 4
    },
    "menikahL": 30,
    "menikahP": 28,
    "duda": 0,
    "janda": 6,
    "lansiaL": 4,
    "lansiaP": 2,
    "totalL": 71,
    "totalP": 61,
    "total": 132
  },
  {
    "no": 37,
    "desa": "NEGLASARI",
    "kelompok": "KAMPUNG MELAYU",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 30,
    "generus": {
      "balitaL": 5,
      "balitaP": 2,
      "paudL": 0,
      "paudP": 2,
      "cabeRawitL": 7,
      "cabeRawitP": 6,
      "preRemajaL": 0,
      "preRemajaP": 2,
      "remajaL": 2,
      "remajaP": 4,
      "pranikahL": 8,
      "pranikahP": 7
    },
    "menikahL": 19,
    "menikahP": 18,
    "duda": 3,
    "janda": 5,
    "lansiaL": 2,
    "lansiaP": 1,
    "totalL": 44,
    "totalP": 46,
    "total": 90
  },
  {
    "no": 38,
    "desa": "PANUNGGANGAN",
    "kelompok": "SAWAH DALAM 1",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 66,
    "generus": {
      "balitaL": 4,
      "balitaP": 10,
      "paudL": 5,
      "paudP": 5,
      "cabeRawitL": 11,
      "cabeRawitP": 7,
      "preRemajaL": 5,
      "preRemajaP": 7,
      "remajaL": 10,
      "remajaP": 14,
      "pranikahL": 81,
      "pranikahP": 21
    },
    "menikahL": 61,
    "menikahP": 57,
    "duda": 1,
    "janda": 9,
    "lansiaL": 9,
    "lansiaP": 7,
    "totalL": 178,
    "totalP": 130,
    "total": 308
  },
  {
    "no": 39,
    "desa": "PANUNGGANGAN",
    "kelompok": "SAWAH DALAM 2",
    "diupdatePada": "-",
    "jumlahKK": 0,
    "generus": {
      "balitaL": 0,
      "balitaP": 0,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 0,
      "cabeRawitP": 0,
      "preRemajaL": 0,
      "preRemajaP": 0,
      "remajaL": 0,
      "remajaP": 0,
      "pranikahL": 0,
      "pranikahP": 0
    },
    "menikahL": 0,
    "menikahP": 0,
    "duda": 0,
    "janda": 0,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 0,
    "totalP": 0,
    "total": 0
  },
  {
    "no": 40,
    "desa": "PANUNGGANGAN",
    "kelompok": "PANUNGGANGAN UTARA",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 51,
    "generus": {
      "balitaL": 10,
      "balitaP": 7,
      "paudL": 0,
      "paudP": 2,
      "cabeRawitL": 10,
      "cabeRawitP": 13,
      "preRemajaL": 3,
      "preRemajaP": 4,
      "remajaL": 7,
      "remajaP": 9,
      "pranikahL": 46,
      "pranikahP": 19
    },
    "menikahL": 34,
    "menikahP": 35,
    "duda": 1,
    "janda": 4,
    "lansiaL": 5,
    "lansiaP": 6,
    "totalL": 111,
    "totalP": 93,
    "total": 204
  },
  {
    "no": 41,
    "desa": "PANUNGGANGAN",
    "kelompok": "PAKULONAN",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 14,
    "generus": {
      "balitaL": 3,
      "balitaP": 1,
      "paudL": 0,
      "paudP": 0,
      "cabeRawitL": 2,
      "cabeRawitP": 1,
      "preRemajaL": 0,
      "preRemajaP": 0,
      "remajaL": 0,
      "remajaP": 1,
      "pranikahL": 19,
      "pranikahP": 4
    },
    "menikahL": 15,
    "menikahP": 13,
    "duda": 0,
    "janda": 3,
    "lansiaL": 3,
    "lansiaP": 4,
    "totalL": 39,
    "totalP": 23,
    "total": 62
  },
  {
    "no": 42,
    "desa": "TANAH TINGGI",
    "kelompok": "KARANGSAWAH",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 37,
    "generus": {
      "balitaL": 9,
      "balitaP": 3,
      "paudL": 9,
      "paudP": 7,
      "cabeRawitL": 4,
      "cabeRawitP": 5,
      "preRemajaL": 7,
      "preRemajaP": 2,
      "remajaL": 8,
      "remajaP": 5,
      "pranikahL": 17,
      "pranikahP": 15
    },
    "menikahL": 38,
    "menikahP": 41,
    "duda": 0,
    "janda": 5,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 92,
    "totalP": 83,
    "total": 175
  },
  {
    "no": 43,
    "desa": "TANAH TINGGI",
    "kelompok": "BUARAN INDAH",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 54,
    "generus": {
      "balitaL": 4,
      "balitaP": 6,
      "paudL": 4,
      "paudP": 7,
      "cabeRawitL": 6,
      "cabeRawitP": 7,
      "preRemajaL": 6,
      "preRemajaP": 4,
      "remajaL": 2,
      "remajaP": 6,
      "pranikahL": 28,
      "pranikahP": 28
    },
    "menikahL": 47,
    "menikahP": 49,
    "duda": 0,
    "janda": 4,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 97,
    "totalP": 111,
    "total": 208
  },
  {
    "no": 44,
    "desa": "TANAH TINGGI",
    "kelompok": "BTN",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 23,
    "generus": {
      "balitaL": 0,
      "balitaP": 3,
      "paudL": 2,
      "paudP": 2,
      "cabeRawitL": 3,
      "cabeRawitP": 2,
      "preRemajaL": 1,
      "preRemajaP": 1,
      "remajaL": 4,
      "remajaP": 1,
      "pranikahL": 8,
      "pranikahP": 8
    },
    "menikahL": 17,
    "menikahP": 21,
    "duda": 0,
    "janda": 2,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 35,
    "totalP": 40,
    "total": 75
  },
  {
    "no": 45,
    "desa": "TANAH TINGGI",
    "kelompok": "PORIS GAGA BARU",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 28,
    "generus": {
      "balitaL": 12,
      "balitaP": 11,
      "paudL": 6,
      "paudP": 7,
      "cabeRawitL": 5,
      "cabeRawitP": 6,
      "preRemajaL": 6,
      "preRemajaP": 4,
      "remajaL": 6,
      "remajaP": 3,
      "pranikahL": 9,
      "pranikahP": 6
    },
    "menikahL": 23,
    "menikahP": 26,
    "duda": 0,
    "janda": 3,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 67,
    "totalP": 66,
    "total": 133
  },
  {
    "no": 46,
    "desa": "TANAH TINGGI",
    "kelompok": "CIPONDOH",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 57,
    "generus": {
      "balitaL": 8,
      "balitaP": 7,
      "paudL": 4,
      "paudP": 4,
      "cabeRawitL": 5,
      "cabeRawitP": 4,
      "preRemajaL": 2,
      "preRemajaP": 7,
      "remajaL": 4,
      "remajaP": 3,
      "pranikahL": 28,
      "pranikahP": 13
    },
    "menikahL": 40,
    "menikahP": 44,
    "duda": 0,
    "janda": 6,
    "lansiaL": 0,
    "lansiaP": 0,
    "totalL": 91,
    "totalP": 88,
    "total": 179
  },
  {
    "no": 47,
    "desa": "TANGERANG",
    "kelompok": "BATUCEPER",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 32,
    "generus": {
      "balitaL": 3,
      "balitaP": 3,
      "paudL": 1,
      "paudP": 1,
      "cabeRawitL": 2,
      "cabeRawitP": 2,
      "preRemajaL": 1,
      "preRemajaP": 4,
      "remajaL": 2,
      "remajaP": 2,
      "pranikahL": 11,
      "pranikahP": 14
    },
    "menikahL": 32,
    "menikahP": 31,
    "duda": 2,
    "janda": 3,
    "lansiaL": 4,
    "lansiaP": 2,
    "totalL": 54,
    "totalP": 60,
    "total": 114
  },
  {
    "no": 48,
    "desa": "TANGERANG",
    "kelompok": "BATUCEPER TIMUR",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 28,
    "generus": {
      "balitaL": 3,
      "balitaP": 1,
      "paudL": 5,
      "paudP": 3,
      "cabeRawitL": 8,
      "cabeRawitP": 8,
      "preRemajaL": 5,
      "preRemajaP": 3,
      "remajaL": 4,
      "remajaP": 6,
      "pranikahL": 10,
      "pranikahP": 7
    },
    "menikahL": 28,
    "menikahP": 32,
    "duda": 2,
    "janda": 2,
    "lansiaL": 2,
    "lansiaP": 2,
    "totalL": 65,
    "totalP": 62,
    "total": 127
  },
  {
    "no": 49,
    "desa": "TANGERANG",
    "kelompok": "BATUSARI",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 17,
    "generus": {
      "balitaL": 3,
      "balitaP": 2,
      "paudL": 4,
      "paudP": 3,
      "cabeRawitL": 6,
      "cabeRawitP": 5,
      "preRemajaL": 2,
      "preRemajaP": 3,
      "remajaL": 3,
      "remajaP": 2,
      "pranikahL": 5,
      "pranikahP": 6
    },
    "menikahL": 17,
    "menikahP": 16,
    "duda": 1,
    "janda": 3,
    "lansiaL": 5,
    "lansiaP": 4,
    "totalL": 41,
    "totalP": 40,
    "total": 81
  },
  {
    "no": 50,
    "desa": "TANGERANG",
    "kelompok": "KARANGSARI1",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 36,
    "generus": {
      "balitaL": 4,
      "balitaP": 2,
      "paudL": 5,
      "paudP": 1,
      "cabeRawitL": 4,
      "cabeRawitP": 9,
      "preRemajaL": 1,
      "preRemajaP": 4,
      "remajaL": 4,
      "remajaP": 3,
      "pranikahL": 12,
      "pranikahP": 9
    },
    "menikahL": 19,
    "menikahP": 19,
    "duda": 4,
    "janda": 10,
    "lansiaL": 6,
    "lansiaP": 12,
    "totalL": 53,
    "totalP": 57,
    "total": 110
  },
  {
    "no": 51,
    "desa": "TANGERANG",
    "kelompok": "KARANGSARI2",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 27,
    "generus": {
      "balitaL": 6,
      "balitaP": 4,
      "paudL": 3,
      "paudP": 5,
      "cabeRawitL": 4,
      "cabeRawitP": 6,
      "preRemajaL": 4,
      "preRemajaP": 4,
      "remajaL": 2,
      "remajaP": 4,
      "pranikahL": 3,
      "pranikahP": 11
    },
    "menikahL": 27,
    "menikahP": 31,
    "duda": 2,
    "janda": 5,
    "lansiaL": 2,
    "lansiaP": 4,
    "totalL": 51,
    "totalP": 70,
    "total": 121
  },
  {
    "no": 52,
    "desa": "TANGERANG",
    "kelompok": "KOMPLEK",
    "diupdatePada": "9-Sep-2026",
    "jumlahKK": 47,
    "generus": {
      "balitaL": 6,
      "balitaP": 2,
      "paudL": 3,
      "paudP": 3,
      "cabeRawitL": 5,
      "cabeRawitP": 4,
      "preRemajaL": 2,
      "preRemajaP": 3,
      "remajaL": 2,
      "remajaP": 3,
      "pranikahL": 14,
      "pranikahP": 17
    },
    "menikahL": 29,
    "menikahP": 33,
    "duda": 4,
    "janda": 6,
    "lansiaL": 11,
    "lansiaP": 7,
    "totalL": 65,
    "totalP": 71,
    "total": 136
  }
];
